stages:
  - build
  - test

build:
  image: maven:3.8-openjdk-17
  stage: build
  script:
    - mvn clean package

test:
  image: maven:3.8-openjdk-17
  stage: test
  script:
    - mvn test -Dtest=com.regnosys.rosetta.interpreternew.*


# java-build:
#   # select the most appropriate image for your project
#   image: maven:3.8-openjdk-11
#   stage: build
#   script:
#     - mvn package -DskipTests=true


# test-job1:
#   stage: test
#   script:
#     - echo "This job tests something"

# test-job2:
#   stage: test
#   script:
#     - echo "This job tests something, but takes more time than test-job1."
#     - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
#     - echo "which simulates a test that runs 20 seconds longer than test-job1"
#     - sleep 20